package com.example.models

import kotlinx.serialization.Serializable

@Serializable
data class AnalyticsDashboardResponse(
    val currentFocusScore: Int,
    val trendPercentage: String,
    val weeklyScores: List<Int>, // For FocusScoreCard Canvas
    val deepWorkHours: String,   // e.g., "5.2h"
    val cognitivePeak: String,   // Generated by ML
    val consistencyGain: String, // Generated by ML
    val contextSwitches: Int
)